package Biblioteca;


/**
* Biblioteca/_GestionBibliotecaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* viernes 15 de marzo de 2024 23H51' CET
*/


// Define la interfaz para el sistema de gestión de la biblioteca
public class _GestionBibliotecaStub extends org.omg.CORBA.portable.ObjectImpl implements Biblioteca.GestionBiblioteca
{


  // Busca un libro por título y devuelve los detalles del libro
  public Biblioteca.Libro buscarLibro (String titulo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscarLibro", true);
                $out.write_string (titulo);
                $in = _invoke ($out);
                Biblioteca.Libro $result = Biblioteca.LibroHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscarLibro (titulo        );
            } finally {
                _releaseReply ($in);
            }
  } // buscarLibro


  // Presta un libro, cambiando su estado a no disponible
  public boolean prestarLibro (String ISBN)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("prestarLibro", true);
                $out.write_string (ISBN);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return prestarLibro (ISBN        );
            } finally {
                _releaseReply ($in);
            }
  } // prestarLibro


  // Devuelve un libro, cambiando su estado a disponible
  public boolean devolverLibro (String ISBN)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("devolverLibro", true);
                $out.write_string (ISBN);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return devolverLibro (ISBN        );
            } finally {
                _releaseReply ($in);
            }
  } // devolverLibro


  //Contar libros por autor
  public int contarLibrosPorAutor (String autor)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("contarLibrosPorAutor", true);
                $out.write_string (autor);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return contarLibrosPorAutor (autor        );
            } finally {
                _releaseReply ($in);
            }
  } // contarLibrosPorAutor


  //contar libros por editorial
  public int contarLibrosPorEditorial (String editorial)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("contarLibrosPorEditorial", true);
                $out.write_string (editorial);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return contarLibrosPorEditorial (editorial        );
            } finally {
                _releaseReply ($in);
            }
  } // contarLibrosPorEditorial


  //listar todos los libros disponibles
  public void listarLibrosDisponibles ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarLibrosDisponibles", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                listarLibrosDisponibles (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarLibrosDisponibles

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Biblioteca/GestionBiblioteca:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionBibliotecaStub
