package Biblioteca;


/**
* Biblioteca/GestionBibliotecaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* viernes 15 de marzo de 2024 23H51' CET
*/


// Define la interfaz para el sistema de gestión de la biblioteca
public interface GestionBibliotecaOperations 
{

  // Busca un libro por título y devuelve los detalles del libro
  Biblioteca.Libro buscarLibro (String titulo);

  // Presta un libro, cambiando su estado a no disponible
  boolean prestarLibro (String ISBN);

  // Devuelve un libro, cambiando su estado a disponible
  boolean devolverLibro (String ISBN);

  //Contar libros por autor
  int contarLibrosPorAutor (String autor);

  //contar libros por editorial
  int contarLibrosPorEditorial (String editorial);

  //listar todos los libros disponibles
  void listarLibrosDisponibles ();
} // interface GestionBibliotecaOperations
